# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agent-toolkit-for-aws = {
    pname = "agent-toolkit-for-aws";
    version = "decfb6feff04765401800d763a02a4e696edd12d";
    src = fetchFromGitHub {
      owner = "aws";
      repo = "agent-toolkit-for-aws";
      rev = "decfb6feff04765401800d763a02a4e696edd12d";
      fetchSubmodules = false;
      sha256 = "sha256-3arfchbkrKgOQIc5g3HO+uliPpM9syd/E+jUhjuWecQ=";
    };
    date = "2026-09-29";
  };
  bento = {
    pname = "bento";
    version = "3a26dba7ee53d047b92602efd2c1d83bf443f611";
    src = fetchFromGitHub {
      owner = "nyblnet";
      repo = "bento";
      rev = "3a26dba7ee53d047b92602efd2c1d83bf443f611";
      fetchSubmodules = false;
      sha256 = "sha256-mbLHpptQOKYBOiTfMxPDQ9e/SWD3X/tGHLQr+Q982iU=";
    };
    date = "2026-09-28";
  };
  claude-mem = {
    pname = "claude-mem";
    version = "ade13f3067d3de486f41dbd8ed90ac5c854de718";
    src = fetchFromGitHub {
      owner = "thedotmack";
      repo = "claude-mem";
      rev = "ade13f3067d3de486f41dbd8ed90ac5c854de718";
      fetchSubmodules = false;
      sha256 = "sha256-xQB3eRT34T2zDDMeGl27Bsvv4KBSuf7i6WTM0TOHz8g=";
    };
    date = "2026-09-28";
  };
  cursor-plugins = {
    pname = "cursor-plugins";
    version = "4b4d98e5e3b3c139f63dbc1ce4b538954c8f2f52";
    src = fetchFromGitHub {
      owner = "cursor";
      repo = "plugins";
      rev = "4b4d98e5e3b3c139f63dbc1ce4b538954c8f2f52";
      fetchSubmodules = false;
      sha256 = "sha256-3oK5younDPDhX/fNPCtDNVotsGgd0lidFZqY5x5RhnA=";
    };
    date = "2026-09-29";
  };
  difit = {
    pname = "difit";
    version = "82a765c037ec28fe7fe90ab2f1e4b5748032b4fa";
    src = fetchFromGitHub {
      owner = "yoshiko-pg";
      repo = "difit";
      rev = "82a765c037ec28fe7fe90ab2f1e4b5748032b4fa";
      fetchSubmodules = false;
      sha256 = "sha256-1EoC5t+8KjNmwKg5lFLig26tzCnp2byhkeGjctVdRls=";
    };
    date = "2026-08-29";
  };
  druk-linux = {
    pname = "druk-linux";
    version = "1.36.0";
    src = fetchurl {
      url = "https://github.com/letstri/druk/releases/download/v1.36.0/druk-linux-x64.tar.gz";
      sha256 = "sha256-crhizlrMeuXSbObxd+r70QV9ltfpvZmYfoXleKe4Nis=";
    };
  };
  druk-mac = {
    pname = "druk-mac";
    version = "1.36.0";
    src = fetchurl {
      url = "https://github.com/letstri/druk/releases/download/v1.36.0/druk-darwin-arm64.zip";
      sha256 = "sha256-Iz4fmUV2NYp0ay7ON5Zp5l0BNSLJlvFtwmVeJypBHGk=";
    };
  };
  eglot-booster = {
    pname = "eglot-booster";
    version = "510f579409627c333ef0e9157db713b1004da842";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "eglot-booster";
      rev = "510f579409627c333ef0e9157db713b1004da842";
      fetchSubmodules = false;
      sha256 = "sha256-HhWR40j/WFcorp8QttXtOz5yxL1B4JUXL+9IuNpoND0=";
    };
    date = "2026-06-30";
  };
  elio = {
    pname = "elio";
    version = "v1.12.0";
    src = fetchFromGitHub {
      owner = "elio-fm";
      repo = "elio";
      rev = "v1.12.0";
      fetchSubmodules = false;
      sha256 = "sha256-FT5F3L8IgbX6vPjEd+TSudoyIZe4TX7no0FF9C75aaU=";
    };
  };
  fixw = {
    pname = "fixw";
    version = "036d0f2cd2d6e061f5acf0835662f194509f2a46";
    src = fetchFromGitHub {
      owner = "6cdh";
      repo = "racket-fixw";
      rev = "036d0f2cd2d6e061f5acf0835662f194509f2a46";
      fetchSubmodules = false;
      sha256 = "sha256-ep1Y9YfJdZRJdJkMA9FlV1ogK+ed/mLTIRRqZ0bWzu8=";
    };
    date = "2026-06-06";
  };
  helix-mainline = {
    pname = "helix-mainline";
    version = "ba40e547426b0f9896c8bdc699a4ab11f2b37dbc";
    src = fetchFromGitHub {
      owner = "helix-editor";
      repo = "helix";
      rev = "ba40e547426b0f9896c8bdc699a4ab11f2b37dbc";
      fetchSubmodules = false;
      sha256 = "sha256-ZjMduEHRsY0H8OHJ5oiF/AcxOBhIiCBwo7D+g1yYwKc=";
    };
    date = "2026-09-29";
  };
  helix-steel = {
    pname = "helix-steel";
    version = "df595c7dc5729e2712c79dd2e35977e3474b3ec6";
    src = fetchFromGitHub {
      owner = "mattwparas";
      repo = "helix";
      rev = "df595c7dc5729e2712c79dd2e35977e3474b3ec6";
      fetchSubmodules = false;
      sha256 = "sha256-zWOzgArhg4PCgi8AMKLtcttBtchlQJay6atEpobCASk=";
    };
    date = "2026-09-26";
  };
  heptabase = {
    pname = "heptabase";
    version = "1.112.0";
    src = fetchurl {
      url = "https://github.com/heptameta/project-meta/releases/download/v1.112.0/Heptabase-1.112.0.AppImage";
      sha256 = "sha256-OfO0dpzZiCLvub69yLrSUizIivx1hUlo/vKgzuBiBBY=";
    };
  };
  heptabase-cli-skills = {
    pname = "heptabase-cli-skills";
    version = "071646112999b8f6b1c76bb2456273cb7c81a17f";
    src = fetchFromGitHub {
      owner = "heptameta";
      repo = "heptabase-cli-skills";
      rev = "071646112999b8f6b1c76bb2456273cb7c81a17f";
      fetchSubmodules = false;
      sha256 = "sha256-KV5sj4wciyY5jX/k+4Va8ztPborMRVRVxZatoPuvtak=";
    };
    date = "2026-09-07";
  };
  html-parsing = {
    pname = "html-parsing";
    version = "11-0";
    src = fetchurl {
      url = "https://www.neilvandyke.org/racket/html-parsing--11-0.zip";
      sha256 = "sha256-xDedPsTlTen9LEj7a3cuB7tmr+gPcZW4t6BTVib9iu8=";
    };
  };
  jj-mode = {
    pname = "jj-mode";
    version = "7e299b60e536d61e694f75fb7a2d1b922f09a5a5";
    src = fetchFromGitHub {
      owner = "bolivier";
      repo = "jj-mode.el";
      rev = "7e299b60e536d61e694f75fb7a2d1b922f09a5a5";
      fetchSubmodules = false;
      sha256 = "sha256-T48ofbMWweWkZJ1GI6DpH9VEWuTLubcO8xIlfh+Xbso=";
    };
    date = "2026-08-31";
  };
  lean-unicode-hx = {
    pname = "lean-unicode-hx";
    version = "f76cca74d2381235c69c94915729bfb61fed0509";
    src = fetchgit {
      url = "https://git.sr.ht/~lambdair/lean-unicode.hx";
      rev = "f76cca74d2381235c69c94915729bfb61fed0509";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ey6ZLNibKX7ZmAyvN883Fqw+rjyc+oyz5HTPbvg94c4=";
    };
    date = "2026-04-09";
  };
  lean4-mode = {
    pname = "lean4-mode";
    version = "6d4030e494039383664a0c08348a5c137eb4641c";
    src = fetchFromGitHub {
      owner = "leanprover-community";
      repo = "lean4-mode";
      rev = "6d4030e494039383664a0c08348a5c137eb4641c";
      fetchSubmodules = false;
      sha256 = "sha256-FzeGnxjtCpeYbDU3GzadCTnLGtDPoe1q8aTpaZBck7A=";
    };
    date = "2026-09-28";
  };
  lean4-skills = {
    pname = "lean4-skills";
    version = "b6243b85b9b0a0ddff5bb6773889044daf687f8e";
    src = fetchFromGitHub {
      owner = "cameronfreer";
      repo = "lean4-skills";
      rev = "b6243b85b9b0a0ddff5bb6773889044daf687f8e";
      fetchSubmodules = false;
      sha256 = "sha256-p6xs+hNMOpYFwU6Exvo/b69p1xKD0ngqoyNhlz7ATRE=";
    };
    date = "2026-09-29";
  };
  lightpanda-linux = {
    pname = "lightpanda-linux";
    version = "0.4.1";
    src = fetchurl {
      url = "https://github.com/lightpanda-io/browser/releases/download/0.4.1/lightpanda-x86_64-linux";
      sha256 = "sha256-HUCAHnLAvGGyy9PzVivPxG3nt54FaPM/aGtk8uWHYQo=";
    };
  };
  lightpanda-mac = {
    pname = "lightpanda-mac";
    version = "0.4.1";
    src = fetchurl {
      url = "https://github.com/lightpanda-io/browser/releases/download/0.4.1/lightpanda-aarch64-macos";
      sha256 = "sha256-meZ3Oe2M9bmFr3y/p8drK6slexcbLa0hEJvXS087tRA=";
    };
  };
  lightpanda-skill = {
    pname = "lightpanda-skill";
    version = "090c08680dc66a258e8f5138476556027e930e3d";
    src = fetchFromGitHub {
      owner = "lightpanda-io";
      repo = "agent-skill";
      rev = "090c08680dc66a258e8f5138476556027e930e3d";
      fetchSubmodules = false;
      sha256 = "sha256-uLrkf6TLtvpBrU6wcKmS/ib8jaaZGMxMMnF4CruR/4c=";
    };
    date = "2026-08-28";
  };
  mcfly = {
    pname = "mcfly";
    version = "2-2";
    src = fetchurl {
      url = "https://www.neilvandyke.org/racket/mcfly--2-2.zip";
      sha256 = "sha256-9wOGjyjtO6GAV8PmjqO0IUD7MmGkt+v88OJ8N2nPSHg=";
    };
  };
  moonbit-skills = {
    pname = "moonbit-skills";
    version = "8b9f1bad14bc62560dbe3537855379e561a4e066";
    src = fetchFromGitHub {
      owner = "moonbitlang";
      repo = "skills";
      rev = "8b9f1bad14bc62560dbe3537855379e561a4e066";
      fetchSubmodules = false;
      sha256 = "sha256-EdDvxq3qTiQFgI6LPONjdF5wUvNbJS3+lzulKIFMezY=";
    };
    date = "2026-09-18";
  };
  nvim-bqn = {
    pname = "nvim-bqn";
    version = "52d8b49f3ebc32d340e2e2b8dba1f6bbd1873b78";
    src = fetchgit {
      url = "https://git.sr.ht/~detegr/nvim-bqn";
      rev = "52d8b49f3ebc32d340e2e2b8dba1f6bbd1873b78";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5wITedTuUn9BKLqmQtPWeFNOa8dXfPIRpUvPSkNJcas=";
    };
    date = "2023-09-08";
  };
  overeasy = {
    pname = "overeasy";
    version = "4-3";
    src = fetchurl {
      url = "https://www.neilvandyke.org/racket/overeasy--4-3.zip";
      sha256 = "sha256-+DjIwWv2z5bNVS24qRoLTOUnDd2JbL6XNK3wfOWtN5w=";
    };
  };
  racket-langserver = {
    pname = "racket-langserver";
    version = "0c9e8260481eed25fdf3429d1fe67cb88fe2164f";
    src = fetchFromGitHub {
      owner = "jeapostrophe";
      repo = "racket-langserver";
      rev = "0c9e8260481eed25fdf3429d1fe67cb88fe2164f";
      fetchSubmodules = false;
      sha256 = "sha256-edw1JClqBZzX6Tzy6fqv8TEPr402vF4w5As8SmVbJAY=";
    };
    date = "2026-09-29";
  };
  repl-ui-hx = {
    pname = "repl-ui-hx";
    version = "8d21aee4114222f0ce708d1c146598a1ce7ae621";
    src = fetchgit {
      url = "https://github.com/waddie/repl-ui.hx";
      rev = "8d21aee4114222f0ce708d1c146598a1ce7ae621";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-k+pYS0AIUrwZfxHiAMZOdn/7PSaQ2g0kI2UTPBLhkGg=";
    };
  };
  run-command = {
    pname = "run-command";
    version = "ed42a376c4761e10530981c34797e7dde8e5abef";
    src = fetchgit {
      url = "https://github.com/waddie/run-command.scm";
      rev = "ed42a376c4761e10530981c34797e7dde8e5abef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-S6K9/3RB2SJu7eH3UlgPQ37YAF+WQLbvMYVuG7E4q+I=";
    };
  };
  steel = {
    pname = "steel";
    version = "8ed1cbbf7eb4aa9b07a4bf8245e7f42103ec617e";
    src = fetchFromGitHub {
      owner = "mattwparas";
      repo = "steel";
      rev = "8ed1cbbf7eb4aa9b07a4bf8245e7f42103ec617e";
      fetchSubmodules = false;
      sha256 = "sha256-WOvi7L4iHwToSESuP5js1IFLQpYNjJO0oNUAGC3EMuw=";
    };
    date = "2026-09-28";
  };
  sulafat = {
    pname = "sulafat";
    version = "b8e60c090daa39e5125d7e058683bc01c360a223";
    src = fetchgit {
      url = "https://git.sr.ht/~lambdair/sulafat";
      rev = "b8e60c090daa39e5125d7e058683bc01c360a223";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dPPQRI7u6sVp3s2ObXW4jwF8iBTAuZki7KypRuukBqU=";
    };
    date = "2026-07-24";
  };
  superpowers = {
    pname = "superpowers";
    version = "8ca22dba9a94f28898bbce59f2537ff4d87c747d";
    src = fetchFromGitHub {
      owner = "obra";
      repo = "superpowers";
      rev = "8ca22dba9a94f28898bbce59f2537ff4d87c747d";
      fetchSubmodules = false;
      sha256 = "sha256-BWPiXoXV+jePP+wn/Z+Af4iehIL7oei00plaWaTzq8s=";
    };
    date = "2026-09-25";
  };
  terminal-browser-linux = {
    pname = "terminal-browser-linux";
    version = "0.13.0";
    src = fetchurl {
      url = "https://github.com/zenbu-labs/terminal-browser/releases/download/v0.13.0/terminal-browser-linux-x64.tar.gz";
      sha256 = "sha256-ExSiB56U4KI5opOzvoHRU6DgcV5KLKCdYDd9xyusJC4=";
    };
  };
  terminal-browser-mac = {
    pname = "terminal-browser-mac";
    version = "0.13.0";
    src = fetchurl {
      url = "https://github.com/zenbu-labs/terminal-browser/releases/download/v0.13.0/terminal-browser-darwin-arm64.tar.gz";
      sha256 = "sha256-erVu2KgZgoZZCzv5yaUZ/gp2K+yktZ+g8MwHdZ99q/s=";
    };
  };
  tolaria = {
    pname = "tolaria";
    version = "2026.9.24";
    src = fetchurl {
      url = "https://github.com/refactoringhq/tolaria/releases/latest/download/Tolaria_2026.9.24_amd64.AppImage";
      sha256 = "sha256-q8HpHgctRjoqeNTVagHuxt1RUMlwu5F0fRVmYbydrqU=";
    };
  };
  tree-sitter-moonbit = {
    pname = "tree-sitter-moonbit";
    version = "5435c307c6cf2ef0d508a99047b06f35a4308444";
    src = fetchFromGitHub {
      owner = "moonbitlang";
      repo = "tree-sitter-moonbit";
      rev = "5435c307c6cf2ef0d508a99047b06f35a4308444";
      fetchSubmodules = false;
      sha256 = "sha256-UUEjrF6uGwTtFGRjmjw75ky8eDwVwAHOHro48TAI+WM=";
    };
    date = "2026-07-22";
  };
  typst-ts-mode = {
    pname = "typst-ts-mode";
    version = "155bb36cff3afe701a0f6b57bd3fe5c9effaa314";
    src = fetchgit {
      url = "https://codeberg.org/meow_king/typst-ts-mode";
      rev = "155bb36cff3afe701a0f6b57bd3fe5c9effaa314";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6QUPLiEoKD64tozOm0KBvCdwCNMxcUpCVZu9qOEVosk=";
    };
    date = "2026-06-24";
  };
  ui-utils-hx = {
    pname = "ui-utils-hx";
    version = "3262e80706f9d332b83d3ac0f578ffd40e2e0673";
    src = fetchgit {
      url = "https://github.com/waddie/ui-utils.hx";
      rev = "3262e80706f9d332b83d3ac0f578ffd40e2e0673";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ur4qbWalj7yfLD05u8k4BRilpT47A4Jh264N6ewjhvk=";
    };
  };
  uiua = {
    pname = "uiua";
    version = "5071e4a22fd2952617ae995cd3fab737c77753ae";
    src = fetchFromGitHub {
      owner = "Apeiros-46B";
      repo = "uiua.vim";
      rev = "5071e4a22fd2952617ae995cd3fab737c77753ae";
      fetchSubmodules = false;
      sha256 = "sha256-ppTyUS1MZbmZavluI61SsnbzyMrZNEpjVpPrunFFK84=";
    };
    date = "2026-01-29";
  };
  yomiyasu = {
    pname = "yomiyasu";
    version = "e5c6a8443a427726a472e2e560fc8679125ea2b8";
    src = fetchFromGitHub {
      owner = "nanaism";
      repo = "yomiyasu";
      rev = "e5c6a8443a427726a472e2e560fc8679125ea2b8";
      fetchSubmodules = false;
      sha256 = "sha256-dZc9NRFBTl4tEKfSLAIE77smW50M5dEbzn5vzTXduRk=";
    };
    date = "2026-10-02";
  };
  zmk-battery-center-linux = {
    pname = "zmk-battery-center-linux";
    version = "0.12.0";
    src = fetchurl {
      url = "https://github.com/kot149/zmk-battery-center/releases/download/v0.12.0/zmk-battery-center_0.12.0_amd64.AppImage";
      sha256 = "sha256-OBJGrlGqYwPl8IhJkqwCT+jadWWLJv80NTJ9HaRx4iE=";
    };
  };
  zmk-battery-center-mac = {
    pname = "zmk-battery-center-mac";
    version = "0.12.0";
    src = fetchurl {
      url = "https://github.com/kot149/zmk-battery-center/releases/download/v0.12.0/zmk-battery-center_0.12.0_aarch64.app.tar.gz";
      sha256 = "sha256-pwFuniHAZviQQn9djxGcTuJvuUt02jd3XQA93HiE8y4=";
    };
  };
}
