# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agent-toolkit-for-aws = {
    pname = "agent-toolkit-for-aws";
    version = "5c779cf1fd4f26fd7ae88e0598494e6a3c2adc35";
    src = fetchFromGitHub {
      owner = "aws";
      repo = "agent-toolkit-for-aws";
      rev = "5c779cf1fd4f26fd7ae88e0598494e6a3c2adc35";
      fetchSubmodules = false;
      sha256 = "sha256-f1nwRe9brcz6SH+IollPpf+woSg/0pWAk637xV+ttRQ=";
    };
    date = "2026-07-23";
  };
  bento = {
    pname = "bento";
    version = "455517a2b3a55fe655cae6842318cd86d8041915";
    src = fetchFromGitHub {
      owner = "nyblnet";
      repo = "bento";
      rev = "455517a2b3a55fe655cae6842318cd86d8041915";
      fetchSubmodules = false;
      sha256 = "sha256-u4Rl3nv2eOpyo1bPtr4BipTGU1IGLwZc6SoNUcgjdtk=";
    };
    date = "2026-07-24";
  };
  budget_tracker_tui = {
    pname = "budget_tracker_tui";
    version = "6d3ea0b4a98182ea5b01b50a109a8f4f003135b3";
    src = fetchFromGitHub {
      owner = "Feromond";
      repo = "budget_tracker_tui";
      rev = "6d3ea0b4a98182ea5b01b50a109a8f4f003135b3";
      fetchSubmodules = false;
      sha256 = "sha256-Z9ZXm/onOOTPHdyECJ8GpPJdy7qVKJyBN8PsxrdZg7A=";
    };
    date = "2026-07-12";
  };
  claude-mem = {
    pname = "claude-mem";
    version = "c9b46df8bb10c36ef4cefe16948e559bc1800896";
    src = fetchFromGitHub {
      owner = "thedotmack";
      repo = "claude-mem";
      rev = "c9b46df8bb10c36ef4cefe16948e559bc1800896";
      fetchSubmodules = false;
      sha256 = "sha256-8qHJP3sgJnljA5mGLkZDZZJrLIfarBbJsVAu3DlNxcc=";
    };
    date = "2026-07-23";
  };
  difit = {
    pname = "difit";
    version = "46be8dcce205b2b389dff10373811d8e62868ad9";
    src = fetchFromGitHub {
      owner = "yoshiko-pg";
      repo = "difit";
      rev = "46be8dcce205b2b389dff10373811d8e62868ad9";
      fetchSubmodules = false;
      sha256 = "sha256-uX4KeEKBLgXJ5vWpqpZ2PZ1UrtTVfnKZ3GKE+Owm8wc=";
    };
    date = "2026-07-11";
  };
  eglot-booster = {
    pname = "eglot-booster";
    version = "510f579409627c333ef0e9157db713b1004da842";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "eglot-booster";
      rev = "510f579409627c333ef0e9157db713b1004da842";
      fetchSubmodules = false;
      sha256 = "sha256-HhWR40j/WFcorp8QttXtOz5yxL1B4JUXL+9IuNpoND0=";
    };
    date = "2026-06-30";
  };
  elio = {
    pname = "elio";
    version = "v1.11.2";
    src = fetchFromGitHub {
      owner = "elio-fm";
      repo = "elio";
      rev = "v1.11.2";
      fetchSubmodules = false;
      sha256 = "sha256-k+88cWiHi1a+f6oulb5MTCnWrJU4vKPEAHBwq5H9bkQ=";
    };
  };
  helix-mainline = {
    pname = "helix-mainline";
    version = "a47389402cd337aaff7327e5601b9ea3cd8409f9";
    src = fetchFromGitHub {
      owner = "helix-editor";
      repo = "helix";
      rev = "a47389402cd337aaff7327e5601b9ea3cd8409f9";
      fetchSubmodules = false;
      sha256 = "sha256-9YfoHElY9EZwsSri37dwNPiqHBRV45mWXejMn6JkOoE=";
    };
    date = "2026-07-22";
  };
  helix-steel = {
    pname = "helix-steel";
    version = "8d189f46e9c620baa685bdfbe39b7c95928475a0";
    src = fetchFromGitHub {
      owner = "mattwparas";
      repo = "helix";
      rev = "8d189f46e9c620baa685bdfbe39b7c95928475a0";
      fetchSubmodules = false;
      sha256 = "sha256-qYR2f+uSUNsJYbbwSo9bCB+LI7n3NzQDCHXJRmHztDg=";
    };
    date = "2026-07-18";
  };
  heptabase = {
    pname = "heptabase";
    version = "1.98.6";
    src = fetchurl {
      url = "https://github.com/heptameta/project-meta/releases/download/v1.98.6/Heptabase-1.98.6.AppImage";
      sha256 = "sha256-bixJ6kgvETfBTU4CxqyUH/swotowfjU8rZBhVWJOMdQ=";
    };
  };
  heptabase-cli-skills = {
    pname = "heptabase-cli-skills";
    version = "a5751bda7e50d5aa2e8fefd63179f898d575ab26";
    src = fetchFromGitHub {
      owner = "heptameta";
      repo = "heptabase-cli-skills";
      rev = "a5751bda7e50d5aa2e8fefd63179f898d575ab26";
      fetchSubmodules = false;
      sha256 = "sha256-ydP7wBq8yLvdxP+E8kCZAFcjRSQXw4x7pCWQOyLrC9Y=";
    };
    date = "2026-06-05";
  };
  jj-mode = {
    pname = "jj-mode";
    version = "64a59eda9022080dcd7e86c128bb1bc3c92964df";
    src = fetchFromGitHub {
      owner = "bolivier";
      repo = "jj-mode.el";
      rev = "64a59eda9022080dcd7e86c128bb1bc3c92964df";
      fetchSubmodules = false;
      sha256 = "sha256-yN0uUJ6MbO53GGzGRYtwbkGJYFhvK+tpkINclKVp0hs=";
    };
    date = "2026-07-22";
  };
  lean-unicode-hx = {
    pname = "lean-unicode-hx";
    version = "f76cca74d2381235c69c94915729bfb61fed0509";
    src = fetchgit {
      url = "https://git.sr.ht/~lambdair/lean-unicode.hx";
      rev = "f76cca74d2381235c69c94915729bfb61fed0509";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ey6ZLNibKX7ZmAyvN883Fqw+rjyc+oyz5HTPbvg94c4=";
    };
    date = "2026-04-09";
  };
  lean4-mode = {
    pname = "lean4-mode";
    version = "1388f9d1429e38a39ab913c6daae55f6ce799479";
    src = fetchFromGitHub {
      owner = "leanprover-community";
      repo = "lean4-mode";
      rev = "1388f9d1429e38a39ab913c6daae55f6ce799479";
      fetchSubmodules = false;
      sha256 = "sha256-6XFcyqSTx1CwNWqQvIc25cuQMwh3YXnbgr5cDiOCxBk=";
    };
    date = "2025-05-31";
  };
  lean4-skills = {
    pname = "lean4-skills";
    version = "7d04c97741a9e5e79e3d85acf8b52f33b9e86207";
    src = fetchFromGitHub {
      owner = "cameronfreer";
      repo = "lean4-skills";
      rev = "7d04c97741a9e5e79e3d85acf8b52f33b9e86207";
      fetchSubmodules = false;
      sha256 = "sha256-WNvyToFn+nocgWPOgEHW+QXWH7p79wlV+XrjXXmeUzw=";
    };
    date = "2026-07-22";
  };
  moonbit-skills = {
    pname = "moonbit-skills";
    version = "5caf81c57cb2ae45654b8f99c5c8f68c812beb91";
    src = fetchFromGitHub {
      owner = "moonbitlang";
      repo = "skills";
      rev = "5caf81c57cb2ae45654b8f99c5c8f68c812beb91";
      fetchSubmodules = false;
      sha256 = "sha256-sBP5obPF7l4gRdNV5TtCYOIDW+1gJoEmRiex4OQQKak=";
    };
    date = "2026-07-06";
  };
  nael = {
    pname = "nael";
    version = "c1d349746731bbff6bf1887c51eb7a1f3bea5c4c";
    src = fetchgit {
      url = "https://codeberg.org/mekeor/nael";
      rev = "c1d349746731bbff6bf1887c51eb7a1f3bea5c4c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-X3yw0pBgUN71TdPcEPznjq//U5X8P+zctik3nw11RSI=";
    };
    date = "2026-03-09";
  };
  nordic = {
    pname = "nordic";
    version = "9fb62116b891184049c50ca6ffb0d3bc100a1a6e";
    src = fetchFromGitHub {
      owner = "AlexvZyl";
      repo = "nordic.nvim";
      rev = "9fb62116b891184049c50ca6ffb0d3bc100a1a6e";
      fetchSubmodules = false;
      sha256 = "sha256-7Wod7nybP/3i3fMBnRdcNEeIWbbzowiyjTlqax8Fn4g=";
    };
    date = "2026-05-03";
  };
  nvim-bqn = {
    pname = "nvim-bqn";
    version = "52d8b49f3ebc32d340e2e2b8dba1f6bbd1873b78";
    src = fetchgit {
      url = "https://git.sr.ht/~detegr/nvim-bqn";
      rev = "52d8b49f3ebc32d340e2e2b8dba1f6bbd1873b78";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5wITedTuUn9BKLqmQtPWeFNOa8dXfPIRpUvPSkNJcas=";
    };
    date = "2023-09-08";
  };
  racket-langserver = {
    pname = "racket-langserver";
    version = "ab61d6b38a1d7fffd35024241433c62b38681a8c";
    src = fetchFromGitHub {
      owner = "jeapostrophe";
      repo = "racket-langserver";
      rev = "ab61d6b38a1d7fffd35024241433c62b38681a8c";
      fetchSubmodules = false;
      sha256 = "sha256-w0ob/vW6kROQylW3ou6lhLs0Y7hVivHj3xE0wVRl1/c=";
    };
    date = "2026-06-30";
  };
  repl-ui-hx = {
    pname = "repl-ui-hx";
    version = "8d21aee4114222f0ce708d1c146598a1ce7ae621";
    src = fetchgit {
      url = "https://github.com/waddie/repl-ui.hx";
      rev = "8d21aee4114222f0ce708d1c146598a1ce7ae621";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-k+pYS0AIUrwZfxHiAMZOdn/7PSaQ2g0kI2UTPBLhkGg=";
    };
  };
  run-command = {
    pname = "run-command";
    version = "ed42a376c4761e10530981c34797e7dde8e5abef";
    src = fetchgit {
      url = "https://github.com/waddie/run-command.scm";
      rev = "ed42a376c4761e10530981c34797e7dde8e5abef";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-S6K9/3RB2SJu7eH3UlgPQ37YAF+WQLbvMYVuG7E4q+I=";
    };
  };
  steel = {
    pname = "steel";
    version = "3a418c9ea586c1862a8c3a49d6a998436afc8957";
    src = fetchFromGitHub {
      owner = "mattwparas";
      repo = "steel";
      rev = "3a418c9ea586c1862a8c3a49d6a998436afc8957";
      fetchSubmodules = false;
      sha256 = "sha256-vR2izfAXC0oidNtyIzdge04BV6C36wrg1qDDzEKAPeg=";
    };
    date = "2026-07-18";
  };
  sulafat = {
    pname = "sulafat";
    version = "b8e60c090daa39e5125d7e058683bc01c360a223";
    src = fetchgit {
      url = "https://git.sr.ht/~lambdair/sulafat";
      rev = "b8e60c090daa39e5125d7e058683bc01c360a223";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dPPQRI7u6sVp3s2ObXW4jwF8iBTAuZki7KypRuukBqU=";
    };
    date = "2026-07-24";
  };
  superpowers = {
    pname = "superpowers";
    version = "d884ae04edebef577e82ff7c4e143debd0bbec99";
    src = fetchFromGitHub {
      owner = "obra";
      repo = "superpowers";
      rev = "d884ae04edebef577e82ff7c4e143debd0bbec99";
      fetchSubmodules = false;
      sha256 = "sha256-kHdQ9e44doBk2yYW88tMSCqVG8ycYcvJSZlrIziXhpA=";
    };
    date = "2026-07-02";
  };
  tolaria = {
    pname = "tolaria";
    version = "2026.7.22";
    src = fetchurl {
      url = "https://github.com/refactoringhq/tolaria/releases/latest/download/Tolaria_2026.7.22_amd64.AppImage";
      sha256 = "sha256-aJPUVVcrQvCVrPowQWcwBd226EhS4/Pzx8KrjV72t8E=";
    };
  };
  typst-ts-mode = {
    pname = "typst-ts-mode";
    version = "155bb36cff3afe701a0f6b57bd3fe5c9effaa314";
    src = fetchgit {
      url = "https://codeberg.org/meow_king/typst-ts-mode";
      rev = "155bb36cff3afe701a0f6b57bd3fe5c9effaa314";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6QUPLiEoKD64tozOm0KBvCdwCNMxcUpCVZu9qOEVosk=";
    };
    date = "2026-06-24";
  };
  ui-utils-hx = {
    pname = "ui-utils-hx";
    version = "3262e80706f9d332b83d3ac0f578ffd40e2e0673";
    src = fetchgit {
      url = "https://github.com/waddie/ui-utils.hx";
      rev = "3262e80706f9d332b83d3ac0f578ffd40e2e0673";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ur4qbWalj7yfLD05u8k4BRilpT47A4Jh264N6ewjhvk=";
    };
  };
  uiua = {
    pname = "uiua";
    version = "5071e4a22fd2952617ae995cd3fab737c77753ae";
    src = fetchFromGitHub {
      owner = "Apeiros-46B";
      repo = "uiua.vim";
      rev = "5071e4a22fd2952617ae995cd3fab737c77753ae";
      fetchSubmodules = false;
      sha256 = "sha256-ppTyUS1MZbmZavluI61SsnbzyMrZNEpjVpPrunFFK84=";
    };
    date = "2026-01-29";
  };
  zmk-battery-center-linux = {
    pname = "zmk-battery-center-linux";
    version = "0.10.1";
    src = fetchurl {
      url = "https://github.com/kot149/zmk-battery-center/releases/download/v0.10.1/zmk-battery-center_0.10.1_amd64.AppImage";
      sha256 = "sha256-NQ4xGNey4ohHLW1biLYYVoe2dTWX8dQib7+7VWQHFAo=";
    };
  };
  zmk-battery-center-mac = {
    pname = "zmk-battery-center-mac";
    version = "0.10.1";
    src = fetchurl {
      url = "https://github.com/kot149/zmk-battery-center/releases/download/v0.10.1/zmk-battery-center_0.10.1_aarch64.app.tar.gz";
      sha256 = "sha256-GkMl10RIQojNBBXlqfsnh9h/2iV3VkRZtoNf/h+afj0=";
    };
  };
}
