# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  budget_tracker_tui = {
    pname = "budget_tracker_tui";
    version = "6410a415d3ad27282a6f82f77328d194e99839e7";
    src = fetchFromGitHub {
      owner = "Feromond";
      repo = "budget_tracker_tui";
      rev = "6410a415d3ad27282a6f82f77328d194e99839e7";
      fetchSubmodules = false;
      sha256 = "sha256-jNZbFz9p8Ed1iqG5CMKq/H0ddQk/Y1th1S+FiKvTb7E=";
    };
    date = "2026-03-31";
  };
  difit = {
    pname = "difit";
    version = "bfc5825c5ded08257b4288e98fe711c61f714568";
    src = fetchFromGitHub {
      owner = "yoshiko-pg";
      repo = "difit";
      rev = "bfc5825c5ded08257b4288e98fe711c61f714568";
      fetchSubmodules = false;
      sha256 = "sha256-FXxHxujI1hM0LmWm+y9dFiQdtU9GmQmwrbDsegGlSwk=";
    };
    date = "2026-04-06";
  };
  eglot-booster = {
    pname = "eglot-booster";
    version = "cab7803c4f0adc7fff9da6680f90110674bb7a22";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "eglot-booster";
      rev = "cab7803c4f0adc7fff9da6680f90110674bb7a22";
      fetchSubmodules = false;
      sha256 = "sha256-xUBQrQpw+JZxcqT1fy/8C2tjKwa7sLFHXamBm45Fa4Y=";
    };
    date = "2025-07-16";
  };
  helix-steel = {
    pname = "helix-steel";
    version = "9738d1fd84eff3fb48e29637bf28826ea64a655b";
    src = fetchFromGitHub {
      owner = "mattwparas";
      repo = "helix";
      rev = "9738d1fd84eff3fb48e29637bf28826ea64a655b";
      fetchSubmodules = false;
      sha256 = "sha256-SYie7U6/Iv+ZDiUIaISToWfGko6VqIjuE5PVOiMUutc=";
    };
    date = "2026-04-03";
  };
  heptabase = {
    pname = "heptabase";
    version = "1.90.0";
    src = fetchurl {
      url = "https://github.com/heptameta/project-meta/releases/download/v1.90.0/Heptabase-1.90.0.AppImage";
      sha256 = "sha256-4xcw3bJTbSvtrg6p1pcOoyQfgADZvdWh3FjBEYAcjYg=";
    };
  };
  jj-mode = {
    pname = "jj-mode";
    version = "6237dca6d48deb699d30ed0c1ff32cbb62eb4fcc";
    src = fetchFromGitHub {
      owner = "bolivier";
      repo = "jj-mode.el";
      rev = "6237dca6d48deb699d30ed0c1ff32cbb62eb4fcc";
      fetchSubmodules = false;
      sha256 = "sha256-RsgAnwJ44AXA/KhgPwzJnj2+6xiCRrzFCvvJLNrqWic=";
    };
    date = "2026-03-06";
  };
  lean-unicode-hx = {
    pname = "lean-unicode-hx";
    version = "6ae1a85886ceefee78f9fcf6055721b14090c23d";
    src = fetchgit {
      url = "https://git.sr.ht/~lambdair/lean-unicode.hx";
      rev = "6ae1a85886ceefee78f9fcf6055721b14090c23d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-9f0MCPwwL3z98IVh1EbRPyyB9QkSvsdWIXBwrLK2N6Q=";
    };
    date = "2026-04-02";
  };
  lean4-mode = {
    pname = "lean4-mode";
    version = "1388f9d1429e38a39ab913c6daae55f6ce799479";
    src = fetchFromGitHub {
      owner = "leanprover-community";
      repo = "lean4-mode";
      rev = "1388f9d1429e38a39ab913c6daae55f6ce799479";
      fetchSubmodules = false;
      sha256 = "sha256-6XFcyqSTx1CwNWqQvIc25cuQMwh3YXnbgr5cDiOCxBk=";
    };
    date = "2025-05-31";
  };
  nael = {
    pname = "nael";
    version = "c1d349746731bbff6bf1887c51eb7a1f3bea5c4c";
    src = fetchgit {
      url = "https://codeberg.org/mekeor/nael";
      rev = "c1d349746731bbff6bf1887c51eb7a1f3bea5c4c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-X3yw0pBgUN71TdPcEPznjq//U5X8P+zctik3nw11RSI=";
    };
    date = "2026-03-09";
  };
  nordic = {
    pname = "nordic";
    version = "9f757428264ef1fcd1703e17702d3a28f307a2f7";
    src = fetchFromGitHub {
      owner = "AlexvZyl";
      repo = "nordic.nvim";
      rev = "9f757428264ef1fcd1703e17702d3a28f307a2f7";
      fetchSubmodules = false;
      sha256 = "sha256-Becp5tPJyjgyVH3BVN6XMKdinZ7JjJ2Czj6c73p6AAk=";
    };
    date = "2026-04-05";
  };
  nvim-bqn = {
    pname = "nvim-bqn";
    version = "52d8b49f3ebc32d340e2e2b8dba1f6bbd1873b78";
    src = fetchgit {
      url = "https://git.sr.ht/~detegr/nvim-bqn";
      rev = "52d8b49f3ebc32d340e2e2b8dba1f6bbd1873b78";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5wITedTuUn9BKLqmQtPWeFNOa8dXfPIRpUvPSkNJcas=";
    };
    date = "2023-09-08";
  };
  racket-langserver = {
    pname = "racket-langserver";
    version = "bafff8b5d5699034567301914a9d40009f4ff72f";
    src = fetchFromGitHub {
      owner = "jeapostrophe";
      repo = "racket-langserver";
      rev = "bafff8b5d5699034567301914a9d40009f4ff72f";
      fetchSubmodules = false;
      sha256 = "sha256-zHEEm9qrPY3hxYu3gbOxf0ykUZLDvQj1P7wBMEQ12i8=";
    };
    date = "2026-03-27";
  };
  steel = {
    pname = "steel";
    version = "605d490c07ae6937d532d5a994920b4dab3016ad";
    src = fetchFromGitHub {
      owner = "mattwparas";
      repo = "steel";
      rev = "605d490c07ae6937d532d5a994920b4dab3016ad";
      fetchSubmodules = false;
      sha256 = "sha256-lqtx1q/AHntbZvF3rpWbicvxE3NGZU+VPMueECaVdSA=";
    };
    date = "2026-04-06";
  };
  sulafat = {
    pname = "sulafat";
    version = "5c7faca6762cc0b5320bcce17ec04216c80d1a40";
    src = fetchgit {
      url = "https://git.sr.ht/~lambdair/sulafat";
      rev = "5c7faca6762cc0b5320bcce17ec04216c80d1a40";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-nAxMGQr7gQlCSjty8DrpXY4GtLcdbxH2aOCaeHCEa2c=";
    };
    date = "2026-03-20";
  };
  typst-ts-mode = {
    pname = "typst-ts-mode";
    version = "cf4d5282988068841efd51dc83f99091b41b91dd";
    src = fetchgit {
      url = "https://codeberg.org/meow_king/typst-ts-mode";
      rev = "cf4d5282988068841efd51dc83f99091b41b91dd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AOL0pIJrPyhBnFPcQHZQjFFvwgRoI+dJ51Kf3oCPplo=";
    };
    date = "2026-03-30";
  };
  uiua = {
    pname = "uiua";
    version = "5071e4a22fd2952617ae995cd3fab737c77753ae";
    src = fetchFromGitHub {
      owner = "Apeiros-46B";
      repo = "uiua.vim";
      rev = "5071e4a22fd2952617ae995cd3fab737c77753ae";
      fetchSubmodules = false;
      sha256 = "sha256-ppTyUS1MZbmZavluI61SsnbzyMrZNEpjVpPrunFFK84=";
    };
    date = "2026-01-29";
  };
}
